[project]
name = "mtailor-mlops-assessment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "onnx>=1.18.0",
    "onnxruntime>=1.22.0",
    "torch==2.2.2",
    "torchvision==0.17.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
